### ISSUE TITLE
Collating does not work on Mac

### ISSUE THREAD

**Issue by sebastianquek** [cs2103t/collate#33]
Collating does not work as expected as Mac uses ~~backslashes~~ forward slashes and filenames can include backslashes.

**Comment by sebastianquek** [comment]
Likely because of this: https://github.com/collate/collate/blob/master/src/main/java/backend/CommandParser.java#L171

``` java
private String standardiseDirectoryString(String directory) {
    return directory.replace(STRING_FORWARD_SLASH, STRING_BACKSLASH);
}
```

**Comment by whipermr5** [comment]
I think you mean they use the forward slash instead of the backslash as a directory separator?

I can confirm that removing the .replace fixes the issue. A backslash is a valid character that can be part of a filename in *nix OSes, so the result of replacing forward slashes with backslashes is that the entire directory string is understood as a single filename to be searched for in the current directory.

**Comment by sebastianquek** [comment]
@whipermr5 Thanks for the heads up, I've updated the description.

**Comment by damithc** [comment]
Anything else to do for this issue?

**Comment by sebastianquek** [comment]
@damithc Yes, I'm currently looking into ensuring the removal of the above line doesn't cause other regressions.

**Comment by damithc** [comment]
Thank @sebastianquek Java might have a abstraction (`File`?) that hides the platform specific string formatting for folder paths.
